### ISSUE TITLE
How can test render performance ?

### ISSUE THREAD

**Issue by nvcken** [CindyLinz/Web-ColorPicker#1]
would you pls tell how can test render performance compare between use WASM vs not

**Comment by CindyLinz** [comment]
Use the slider on the top of the page to enlarge the selection panel. And then press-and-drag the mouse in the selection panel.. With sufficiently large panel size, you should feel obviously laggy with the "Use WASM" checkbox unchecked, while it going well with the checkbox checked.

**Comment by nvcken** [comment]
thanks, does this proof of render performance better with WASM and also bring render with low level language binding to web ?

**Comment by CindyLinz** [comment]
Yes. Though this one is especially fit for WASM that makes an obvious difference.
